### PR TITLE
Universal React components with Figma export

### LINKED ISSUE #22: Create universal components with Figma export
Cross-platform components using `react-primitives` (React Native, React web, React Figma, etc)

Figma entrypoint to render these components to a design.

### PR DESCRIPTION
**Pull request by macintoshhelper**
Fixes #22 

(uses my fork of `styled-components` to patch a feature in, which shouldn't be used long-term)

Includes `<PlaceList>` and `<CategoryList>` components

### CODE REVIEW

**Comment by jamiecoe** [comment]
Hi @macintoshhelper,

Thanks for your help with this!

Presumably we could still use these components even if we switched to a Gatsby project setup, similar to this project structure?

https://github.com/kpennell/acrotagsgatsbyblog

**Comment by jamiecoe** [comment]
Hi @macintoshhelper 

So would these components connect to [Figma design](https://www.figma.com/file/HAfG9PtWmHW4T0HuRMmGRn/Brixton-Local%2Flovelocal.life?node-id=3%3A2)? 

Any chance you could add an example of how they'd work with Gatsby setup?

**Comment by macintoshhelper** [comment]
Hi @jamiecoe 

Yes. These components should work in any React project, just need the standard `styled-components` setup.

Should I merge #24 into my branch: `feat/universal-components`, and work on top of that? Or open a new branch/PR?

**Comment by jamiecoe** [comment]
Hi @macintoshhelper

Yes please, if you could merge the Gatsby branch into yours and add an example of using the components, that would be amazing 🙌

**Comment by macintoshhelper** [comment]
I've merged the Gatsby site in and linked up the universal components to the home-page as a demo.

**Gatsby app**

image

**Figma Style-guide** – exported from the universal `components` folder.

image

**Pull request merged**
