### PR TITLE
Add colours and emoji to tags + hover and category styling

### PR DESCRIPTION
**Pull request by macintoshhelper**
image

### CODE REVIEW

**Comment by Johanna-hub** [comment]
Thanks so much this looks so good with the hover and the colours.  Just a note about the tags, they are free text in the spreadsheet (categories is a drop-down list) - so can be anything.  It is basically up to the person writing it - so they are quite different between locations.  I don't think we can have specific emojis because we will have to update every time there is a new one added to the spreadsheet, for each location.  There are some that will be in all, such as donate, support, plants, fruit+veg, bread etc.  So we could come up with a list of those and then the others can be random?  Or we could choose ones for all the current Brixton tags, and then if a location comes up with a tag that isn't in Brixton - they just get a randomly assigned one?

You are actually using the Lewisham spreadsheet details - I will slack DM you the Brixton one, which has 70 entries, so there are quite a lot more tags than what you were using.  Below is a screenshot of the Brixton tags, as you can see there isn't that much crossover.

Screenshot 2020-05-02 at 19 32. 32

**Comment by macintoshhelper** [comment]
> Thanks so much this looks so good with the hover and the colours. Just a note about the tags, they are free text in the spreadsheet (categories is a drop-down list) - so can be anything. It is basically up to the person writing it - so they are quite different between locations. I don't think we can have specific emojis because we will have to update every time there is a new one added to the spreadsheet, for each location. There are some that will be in all, such as donate, support, plants, fruit+veg, bread etc. So we could come up with a list of those and then the others can be random? Or we could choose ones for all the current Brixton tags, and then if a location comes up with a tag that isn't in Brixton - they just get a randomly assigned one?
> 
> You are actually using the Lewisham spreadsheet details - I will slack DM you the Brixton one, which has 70 entries, so there are quite a lot more tags than what you were using. Below is a screenshot of the Brixton tags, as you can see there isn't that much crossover.
> 
> Screenshot 2020-05-02 at 19 32. 32

Hmm, maybe I could move it into a function/package to return colours based on a keyword, and do something like `if (type.includes('fruit') { color = ...; emoji = ... }`, in a switch case, and have the default as a random colour.

**Comment by Johanna-hub** [comment]
> 
> Hmm, maybe I could move it into a function/package to return colours based on a keyword, and do something like `if (type.includes('fruit') { color = ...; emoji = ... }`, in a switch case, and have the default as a random colour.

Think this sounds like a really good option!  😊

**Comment by macintoshhelper** [comment]
> Think this sounds like a really good option! 😊

I've pushed it up, do you think it's worth leaving the emoji in? Should cover quite a number of tags with the alias system, but might occasionally give the wrong thing, like returning a `car` for `caribbean`, due to the `tagType.includes(...)`, so would need a bit of maintenance. But can update the master repo `tagMeta` JSON. Could even pull this info in from a new page in the spreadsheet.

**Comment by Johanna-hub** [comment]
Sorry - have been deploying the fifth website and doing a bit of a PR push on the Brixton one and having a think about what to do about this.

Thanks so much for doing all the emoji work but I am thinking we might just have to go with colours.  If you look at the tags at the most recent one https://www.winchmorehilllocal.life/tags - they are very different, and as more get launched I am not going to have have time to go through them.  So it is really up to the individual areas and what is popular in their area.

**Comment by macintoshhelper** [comment]
Np, I've commented out/removed the emojis code, so it's just colours now. I'll probably have a go at implementing the emoji bit in its own library later, could be a fun project to use with some data science.

If the tag is found in the tagMeta index, the colour is pre-defined (handpicked colours 😄), but if it's not found, it's randomly generated on each page load.

**Comment by Johanna-hub** [comment]
Great to have the handpicked colours and then the random ones! Thanks so much, would it be possible to remove the blue underline on all the tags on the tags list page please?

**Comment by macintoshhelper** [comment]
Is it removed now? It was removed for WebKit (Chrome), I've done a more general override now.

**Comment by Johanna-hub** [comment]
> Is it removed now? It was removed for WebKit (Chrome), I've done a more general override now.

Yes, sorry - I was on Firefox, which explains it!

**Comment by macintoshhelper** [comment]
Np, site should work/be tested on Firefox

**Pull request merged**
